-- DocuVault schema bootstrap
-- Generated by concatenating init.sql + migration/V*.sql
-- Mount this into a fresh postgres container's /docker-entrypoint-initdb.d/
-- DO NOT apply on a populated database — it is for fresh installs only.

-- ============================================================
-- init.sql (baseline schema)
-- ============================================================
-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Users table
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'VIEWER',
    enabled BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Spaces table (represents a group or repository)
CREATE TABLE IF NOT EXISTS spaces (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    description TEXT,
    type VARCHAR(20) NOT NULL DEFAULT 'REPOSITORY',
    parent_id UUID REFERENCES spaces(id) ON DELETE CASCADE,
    gitlab_project_id INTEGER,
    gitlab_url VARCHAR(500),
    branch VARCHAR(255) DEFAULT 'main',
    sync_enabled BOOLEAN DEFAULT true,
    sync_interval_minutes INTEGER DEFAULT 15,
    last_synced_at TIMESTAMP WITH TIME ZONE,
    last_sync_error VARCHAR(1000),
    last_sync_files_changed INTEGER,
    logo_url VARCHAR(500),
    created_by UUID REFERENCES users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT spaces_slug_parent_unique UNIQUE (slug, parent_id)
);

-- Space permissions (many-to-many between users and spaces)
CREATE TABLE IF NOT EXISTS space_permissions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    space_id UUID REFERENCES spaces(id) ON DELETE CASCADE,
    permission_level VARCHAR(50) NOT NULL DEFAULT 'VIEW',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, space_id)
);

-- Documents table
CREATE TABLE IF NOT EXISTS documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    space_id UUID REFERENCES spaces(id) ON DELETE CASCADE,
    path VARCHAR(1000) NOT NULL,
    title VARCHAR(500),
    content_hash VARCHAR(64),
    last_synced_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(space_id, path)
);

-- Document embeddings for semantic search
CREATE TABLE IF NOT EXISTS document_embeddings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    document_id UUID REFERENCES documents(id) ON DELETE CASCADE,
    chunk_index INTEGER NOT NULL,
    content TEXT NOT NULL,
    embedding vector(1536),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create index for vector similarity search
CREATE INDEX IF NOT EXISTS document_embeddings_embedding_idx
ON document_embeddings USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

-- Chat history
CREATE TABLE IF NOT EXISTS chat_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    space_id UUID REFERENCES spaces(id) ON DELETE CASCADE,
    title VARCHAR(255),
    messages JSONB NOT NULL DEFAULT '[]',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- App settings (key-value store for configuration)
CREATE TABLE IF NOT EXISTS app_settings (
    key VARCHAR(255) PRIMARY KEY,
    value TEXT,
    encrypted BOOLEAN DEFAULT false,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- User invitations
CREATE TABLE IF NOT EXISTS invitations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) NOT NULL,
    space_id UUID REFERENCES spaces(id) ON DELETE CASCADE,
    role VARCHAR(50) NOT NULL DEFAULT 'VIEWER',
    token VARCHAR(255) UNIQUE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    accepted_at TIMESTAMP WITH TIME ZONE,
    created_by UUID REFERENCES users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Password reset tokens
CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) NOT NULL,
    token VARCHAR(255) UNIQUE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Shared links for public file sharing
CREATE TABLE IF NOT EXISTS shared_links (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    token VARCHAR(64) UNIQUE NOT NULL,
    space_id UUID NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
    file_path VARCHAR(1000) NOT NULL,
    created_by UUID NOT NULL REFERENCES users(id),
    expires_at TIMESTAMP WITH TIME ZONE,
    revoked_at TIMESTAMP WITH TIME ZONE,
    password_hash VARCHAR(255),
    share_type VARCHAR(10) NOT NULL DEFAULT 'FILE',
    writable_scopes TEXT NOT NULL DEFAULT '[]',
    access_count INTEGER NOT NULL DEFAULT 0,
    last_accessed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE shared_links ADD COLUMN IF NOT EXISTS writable_scopes TEXT NOT NULL DEFAULT '[]';

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_spaces_slug ON spaces(slug);
CREATE INDEX IF NOT EXISTS idx_spaces_parent_id ON spaces(parent_id);
CREATE INDEX IF NOT EXISTS idx_spaces_type ON spaces(type);
CREATE INDEX IF NOT EXISTS idx_documents_space_id ON documents(space_id);
CREATE INDEX IF NOT EXISTS idx_document_embeddings_document_id ON document_embeddings(document_id);
CREATE INDEX IF NOT EXISTS idx_space_permissions_user_id ON space_permissions(user_id);
CREATE INDEX IF NOT EXISTS idx_space_permissions_space_id ON space_permissions(space_id);
CREATE INDEX IF NOT EXISTS idx_chat_history_user_id ON chat_history(user_id);
CREATE INDEX IF NOT EXISTS idx_invitations_token ON invitations(token);
CREATE INDEX IF NOT EXISTS idx_invitations_email ON invitations(email);
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_token ON password_reset_tokens(token);
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_email ON password_reset_tokens(email);
CREATE INDEX IF NOT EXISTS idx_shared_links_token ON shared_links(token);
CREATE INDEX IF NOT EXISTS idx_shared_links_space_file ON shared_links(space_id, file_path);

-- API tokens for external integrations (MCP server, etc.)
CREATE TABLE IF NOT EXISTS api_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    token_prefix VARCHAR(16) NOT NULL,
    last_used_at TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE,
    revoked_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_api_tokens_token_hash ON api_tokens(token_hash);
CREATE INDEX IF NOT EXISTS idx_api_tokens_user_id ON api_tokens(user_id);

-- ============================================================
-- V001__api_tokens.sql
-- ============================================================
-- API tokens for external integrations (MCP server, etc.)
CREATE TABLE IF NOT EXISTS api_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    token_prefix VARCHAR(16) NOT NULL,
    last_used_at TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE,
    revoked_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_api_tokens_token_hash ON api_tokens(token_hash);
CREATE INDEX IF NOT EXISTS idx_api_tokens_user_id ON api_tokens(user_id);

-- ============================================================
-- V002__shared_links_password_and_type.sql
-- ============================================================
ALTER TABLE shared_links ADD COLUMN password_hash VARCHAR(255);
ALTER TABLE shared_links ADD COLUMN share_type VARCHAR(10) NOT NULL DEFAULT 'FILE';

-- ============================================================
-- V003__user_enabled_field.sql
-- ============================================================
-- Add enabled flag to users table for placeholder/invited users
ALTER TABLE users ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT true;

-- ============================================================
-- V004__inbox_tables.sql
-- ============================================================
-- Routing rules for inbox auto-filing
CREATE TABLE IF NOT EXISTS routing_rules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    space_id UUID NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
    type VARCHAR(20) NOT NULL,
    condition VARCHAR(500) NOT NULL,
    action_type VARCHAR(50) NOT NULL DEFAULT 'APPEND_TO_DOCUMENT',
    target_document_path VARCHAR(1000),
    target_group_path VARCHAR(500),
    auto_file BOOLEAN NOT NULL DEFAULT false,
    description VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_routing_rules_space_id ON routing_rules(space_id);

-- Inbox notes
CREATE TABLE IF NOT EXISTS inbox_notes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    space_id UUID NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
    author_id UUID NOT NULL REFERENCES users(id),
    content TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'UNSORTED',
    ai_suggestion TEXT,
    filed_to_document_path VARCHAR(1000),
    filed_by_id UUID REFERENCES users(id),
    auto_filed BOOLEAN NOT NULL DEFAULT false,
    applied_rule_id UUID REFERENCES routing_rules(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    filed_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_inbox_notes_space_id_status ON inbox_notes(space_id, status);

-- ============================================================
-- V005__space_state.sql
-- ============================================================
CREATE TABLE space_state (
    id          UUID         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    space_id    UUID         NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
    key         VARCHAR(255) NOT NULL,
    value       TEXT         NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    UNIQUE (space_id, key)
);

CREATE INDEX idx_space_state_space_id ON space_state(space_id);

-- ============================================================
-- V006__space_tokens.sql
-- ============================================================
CREATE TABLE space_tokens (
    id           UUID         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    space_id     UUID         NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
    name         VARCHAR(255) NOT NULL,
    token_hash   VARCHAR(64)  NOT NULL UNIQUE,
    token_prefix VARCHAR(16)  NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_used_at TIMESTAMPTZ,
    revoked_at   TIMESTAMPTZ
);

CREATE INDEX idx_space_tokens_space_id  ON space_tokens(space_id);
CREATE INDEX idx_space_tokens_token_hash ON space_tokens(token_hash);

-- ============================================================
-- V007__space_last_push_error.sql
-- ============================================================
ALTER TABLE spaces ADD COLUMN last_push_error VARCHAR(1000);

-- ============================================================
-- V008__annotations.sql
-- ============================================================
-- Add access level to shared links (VIEW = read-only, COMMENT = can annotate)
ALTER TABLE shared_links ADD COLUMN access_level VARCHAR(10) NOT NULL DEFAULT 'VIEW';

-- Annotations table: pinned comments on documents
CREATE TABLE annotations (
    id              UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    space_id        UUID         NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
    file_path       VARCHAR(1000) NOT NULL,

    -- Author: internal user OR anonymous (shared link commenter)
    user_id         UUID         REFERENCES users(id) ON DELETE SET NULL,
    author_name     VARCHAR(255) NOT NULL,

    -- Thread: NULL = top-level, non-NULL = reply
    parent_id       UUID         REFERENCES annotations(id) ON DELETE CASCADE,

    -- Content
    body            TEXT         NOT NULL,

    -- Position anchor (JSONB) — schema depends on render mode:
    --   markdown: {"type":"markdown","xPercent":42.5,"yPercent":18.3,"snippet":"nearby text"}
    --   image:    {"type":"image","xPercent":65.0,"yPercent":30.0}
    --   html:     {"type":"html","elementId":"feat-1","selector":"body>div:nth-child(3)>p","offsetX":35.2,"offsetY":60.1,"xPercent":22.8,"yPercent":41.3}
    --   pdf:      {"type":"pdf","page":1,"xPercent":45.0,"yPercent":60.0}
    -- NULL for replies (they inherit parent's anchor)
    anchor          JSONB,

    -- Resolution lifecycle
    resolved        BOOLEAN      NOT NULL DEFAULT false,
    resolved_by     UUID         REFERENCES users(id) ON DELETE SET NULL,
    resolved_at     TIMESTAMPTZ,

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_annotations_space_file ON annotations(space_id, file_path);
CREATE INDEX idx_annotations_parent ON annotations(parent_id);
CREATE INDEX idx_annotations_user ON annotations(user_id);

-- ============================================================
-- V009__sync_status_and_conflict_fields.sql
-- ============================================================
-- DocuVault uses ddl-auto: validate — this file is documentation; apply manually on the server.

ALTER TABLE spaces ADD COLUMN sync_status VARCHAR(32) NOT NULL DEFAULT 'OK';
ALTER TABLE spaces ADD COLUMN conflict_base_ref VARCHAR(64);
ALTER TABLE spaces ADD COLUMN conflict_branch VARCHAR(255);
ALTER TABLE spaces ADD COLUMN conflict_mr_url VARCHAR(500);
ALTER TABLE spaces ADD COLUMN conflict_mr_iid BIGINT;
ALTER TABLE spaces ADD COLUMN conflict_mr_project_id BIGINT;
ALTER TABLE spaces ADD COLUMN conflict_detected_at TIMESTAMP;

-- Backfill derived status from existing error fields so existing rows start in a sensible state.
UPDATE spaces SET sync_status = 'PUSH_ERROR' WHERE last_push_error IS NOT NULL;
UPDATE spaces SET sync_status = 'SYNC_ERROR' WHERE last_sync_error IS NOT NULL AND last_push_error IS NULL;

-- ============================================================
-- V010__shared_link_access_denials.sql
-- ============================================================
-- Audit table for denied public share access attempts.
-- Applied manually via psql on the server (project uses ddl-auto=validate, no Flyway).

CREATE TABLE IF NOT EXISTS shared_link_access_denials (
    id UUID PRIMARY KEY,
    token VARCHAR(64) NOT NULL,
    reason VARCHAR(32) NOT NULL,
    client_ip VARCHAR(45),
    user_agent VARCHAR(500),
    request_uri VARCHAR(2000),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_denial_token ON shared_link_access_denials(token);
CREATE INDEX IF NOT EXISTS idx_denial_created_at ON shared_link_access_denials(created_at);

-- ============================================================
-- V011__user_push_tokens.sql
-- ============================================================
CREATE TABLE user_push_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    platform VARCHAR(16) NOT NULL CHECK (platform IN ('ios', 'android')),
    token TEXT NOT NULL,
    device_name VARCHAR(120) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, token)
);

CREATE INDEX idx_user_push_tokens_user_id ON user_push_tokens(user_id);
CREATE INDEX idx_user_push_tokens_token ON user_push_tokens(token);

-- ============================================================
-- V012__notifications.sql
-- ============================================================
-- Per-user notification preferences: push and email cadences are independent.
ALTER TABLE users ADD COLUMN push_mode VARCHAR(16) NOT NULL DEFAULT 'INSTANT'
    CHECK (push_mode IN ('INSTANT', 'NONE'));
ALTER TABLE users ADD COLUMN email_mode VARCHAR(16) NOT NULL DEFAULT 'NONE'
    CHECK (email_mode IN ('INSTANT', 'HOURLY', 'DAILY', 'NONE'));

-- Track the last commit we synced so we can diff incrementally
ALTER TABLE spaces ADD COLUMN last_synced_commit_sha VARCHAR(40);

-- Per-space change events emitted during sync (and via MCP-triggered commits)
CREATE TABLE space_change_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    space_id UUID NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
    file_path TEXT NOT NULL,
    old_path TEXT,
    change_type VARCHAR(16) NOT NULL CHECK (change_type IN ('ADDED', 'MODIFIED', 'DELETED', 'RENAMED')),
    commit_sha VARCHAR(40),
    commit_message TEXT,
    commit_author_email VARCHAR(320),
    commit_author_name VARCHAR(255),
    triggered_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    detected_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_space_change_events_space_detected ON space_change_events(space_id, detected_at DESC);
CREATE INDEX idx_space_change_events_detected ON space_change_events(detected_at);

-- Outbox of dispatched notifications (one row per user per event per channel)
CREATE TABLE notification_dispatches (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_id UUID NOT NULL REFERENCES space_change_events(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    channel VARCHAR(16) NOT NULL CHECK (channel IN ('PUSH', 'EMAIL_INSTANT', 'EMAIL_HOURLY', 'EMAIL_DAILY')),
    dispatched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    success BOOLEAN NOT NULL,
    error TEXT,
    UNIQUE (event_id, user_id, channel)
);

CREATE INDEX idx_notification_dispatches_user ON notification_dispatches(user_id, dispatched_at DESC);
