#!/usr/bin/env bash
# Build a customer install bundle for a given DocuVault version.
#
# Usage: scripts/build-install-bundle.sh <version>
#
# Produces dist/docuvault-install-<version>.tar.gz containing:
#   docuvault-install-<version>/
#   ├── INSTALL.md               (from docs/install.md)
#   ├── docker-compose.yml       (from docker-compose.product.yml — renamed)
#   ├── .env.example             (from .env.example.product — renamed)
#   ├── deploy.sh
#   └── db/bootstrap.sql         (regenerated from init.sql + migrations)

set -euo pipefail

VERSION="${1:-}"
if [ -z "$VERSION" ]; then
  echo "Usage: $0 <version>"
  echo "  e.g. $0 v0.1.1"
  exit 1
fi

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# Regenerate bootstrap.sql with idempotency rewrites so re-applying on a
# partially-populated DB (e.g. init.sql already includes some early migrations)
# doesn't fatal-error on duplicate columns/tables/indexes.
rm -f db/bootstrap.sql
mkdir -p db
{
  echo "-- DocuVault schema bootstrap"
  echo "-- Generated by scripts/build-install-bundle.sh from"
  echo "--   backend/src/main/resources/db/init.sql"
  echo "--   backend/src/main/resources/db/migration/V*.sql"
  echo "-- CREATE TABLE/INDEX and ADD COLUMN are rewritten to IF NOT EXISTS so"
  echo "-- migrations whose changes are already in init.sql are silently skipped."
  echo ""
  cat backend/src/main/resources/db/init.sql
  for f in backend/src/main/resources/db/migration/V*.sql; do
    echo ""
    echo "-- ============================================================"
    echo "-- $(basename "$f")"
    echo "-- ============================================================"
    sed -E \
      -e 's/CREATE TABLE (IF NOT EXISTS )?/CREATE TABLE IF NOT EXISTS /g' \
      -e 's/CREATE INDEX (IF NOT EXISTS )?/CREATE INDEX IF NOT EXISTS /g' \
      -e 's/CREATE UNIQUE INDEX (IF NOT EXISTS )?/CREATE UNIQUE INDEX IF NOT EXISTS /g' \
      -e 's/ADD COLUMN (IF NOT EXISTS )?/ADD COLUMN IF NOT EXISTS /g' \
      "$f"
  done
} > db/bootstrap.sql

STAGE_PARENT="$(mktemp -d -t docuvault-install)"
STAGE="$STAGE_PARENT/docuvault-install-$VERSION"
mkdir -p "$STAGE/db"

cp docker-compose.product.yml "$STAGE/docker-compose.yml"
cp .env.example.product       "$STAGE/.env.example"
cp deploy.sh                  "$STAGE/"
chmod +x "$STAGE/deploy.sh"
cp db/bootstrap.sql           "$STAGE/db/"
cp docs/install.md            "$STAGE/INSTALL.md"

mkdir -p dist
ARCHIVE="dist/docuvault-install-$VERSION.tar.gz"
tar -czf "$ARCHIVE" -C "$STAGE_PARENT" "docuvault-install-$VERSION"

echo "==> Bundle:  $ARCHIVE"
echo "==> Size:    $(wc -c < "$ARCHIVE" | tr -d ' ') bytes"
echo "==> sha256:  $(shasum -a 256 "$ARCHIVE" | awk '{print $1}')"
echo ""
echo "==> Contents:"
tar -tzf "$ARCHIVE" | sed 's/^/    /'
