#!/usr/bin/env bash
# Regenerates db/bootstrap.sql, the schema a fresh database starts from.
#
# Flyway baselines a database that already has tables at `baseline-version`
# (application.yml) and from then on applies only newer migrations. So the
# bootstrap must contain init.sql plus EXACTLY the migrations up to that
# version: a migration left out never runs on fresh installs, one too many
# runs twice. CREATE TABLE/INDEX and ADD COLUMN are rewritten to IF NOT EXISTS
# because init.sql already contains parts of the early migrations.
#
# Usage: scripts/generate-bootstrap.sh   (run after changing init.sql or the baseline)
set -euo pipefail

cd "$(dirname "$0")/.."
RESOURCES=backend/src/main/resources
BASELINE="$(sed -nE 's/^ *baseline-version: *([0-9]+).*/\1/p' "$RESOURCES/application.yml" | head -1)"
[ -n "$BASELINE" ] || { echo "baseline-version not found in application.yml" >&2; exit 1; }

{
  echo "-- DocuVault schema bootstrap, generated by scripts/generate-bootstrap.sh"
  echo "-- from db/init.sql and db/migration/V*.sql up to the Flyway baseline (V$BASELINE)."
  echo "-- Do not edit by hand."
  echo ""
  cat "$RESOURCES/db/init.sql"
  for f in "$RESOURCES"/db/migration/V*.sql; do
    version="$(basename "$f" | sed -E 's/^V0*([0-9]+)__.*/\1/')"
    [ "$version" -le "$BASELINE" ] || continue
    echo ""
    echo "-- ============================================================"
    echo "-- $(basename "$f")"
    echo "-- ============================================================"
    sed -E \
      -e 's/CREATE TABLE (IF NOT EXISTS )?/CREATE TABLE IF NOT EXISTS /g' \
      -e 's/CREATE INDEX (IF NOT EXISTS )?/CREATE INDEX IF NOT EXISTS /g' \
      -e 's/CREATE UNIQUE INDEX (IF NOT EXISTS )?/CREATE UNIQUE INDEX IF NOT EXISTS /g' \
      -e 's/ADD COLUMN (IF NOT EXISTS )?/ADD COLUMN IF NOT EXISTS /g' \
      "$f"
  done
} > db/bootstrap.sql
echo "==> db/bootstrap.sql regenerated (init.sql + V001..V$BASELINE)"
